version: "3.8"

services:
  item-db:
    container_name: item-db
    image: mongo:3
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER 
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD 
    ports:
      - 27017:27017    
    networks:
      - network-item-app  
    volumes:
      - app-db:/data/db

  item-app:
    container_name: item-app  
    image: qrizan/item-app:v1
    restart: on-failure
    ports:
      - 80:8080
    environment:
      NODE_ENV: production
      DB_HOST: item-db
    depends_on:
      - item-db
    networks:
      - network-item-app        

volumes:
  app-db:
    name: app-db

networks:
  network-item-app:
    name: network-item-app
    driver: bridge