# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "karsajobs" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Lint Dockerfile
      run: docker run --rm -i hadolint/hadolint < Dockerfile
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.15

    - name: Test app
      run: go test -v -short --count=1 $(go list ./...)

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}     
                    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/qrizan/karsajobs:latest
